alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias gitclean='git branch --merged | egrep -v "(^\*|master|main|dev)" | xargs git branch -d'
alias gitcleansqmaster='git checkout -q master && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base master $branch) && [[ $(git cherry master $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]]     && git branch -D $branch; done'
alias gitcleansqmain='git checkout -q main && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base main $branch) && [[ $(git cherry main $(git commit-tree $(git rev-parse "$branch^{tree}") -p $mergeBase -m _)) == "-"* ]]     && git branch -D $branch; done'
